import Dummy_Profile from '../../media/dummy_profile.jpg';

const  dummy_posts =[

        {
            age_group: "31-35 yrs",
            country: "India",
            description: "He is not found.. yet..",
            disability: "Not Disbaled",
            dp_image: "https://firebasestorage.googleapis.com/v0/b/firsttry-4edb6.appspot.com/o/images%2FFB_IMG_15182850734166532.jpg?alt=media&token=fb301368-6bab-4307-b054-457b1a1bd724",
            follwed_by: [],
            gender: "male",
            location: "Andheri",
            name: "Ghulam Raza",
            notification_id: "786000",
            post_creator_email: "assdf@gmail.com",
            post_creator_name: "Sultan",
            post_id: "789177930000",
            post_status: "active", //active, disabled, resolved, reported
            post_time: {date: 28, month: 6, year: 2020},
            region: "Delhi",
            status: "missing",
                  isReported: false,
      reported_by: 'Selcen',
        },
        {
            age_group: "21-25 yrs",
            country: "Pakistan",
            description: "He is not missed.. yet..",
            disability: "Physical Disability",
            // dp_image: "https://firebasestorage.googleapis.com/v0/b/firsttry-4edb6.appspot.com/o/images%2Ffaizan.jpg?alt=media&token=d7822c6f-6e47-4a88-b30d-c7e5beea5c0c",
            dp_image: 'https://firebasestorage.googleapis.com/v0/b/firsttry-4edb6.appspot.com/o/images%2FFB_IMG_15062661956359364.jpg?alt=media&token=fe994214-8a33-4785-a23b-84fc6829cd1b',
            follwed_by: [],
            gender: "female",
            location: "Ghulshan Iqbal",
            name: "Maruti",
            notification_id: "786001",
            post_creator_email: "asdf@gmail.com",
            post_creator_name: "Sultan",
            post_id: "789177930001",
            post_status: "active",
            post_time: {date: 20, month: 6, year: 2020},
            region: "Punjab",
            status: "found",
                  isReported: true,
      reported_by: 'Gokcin',
        },
        {
            age_group: "11-15 yrs",
            country: "Pakistan",
            description: "He is not missed.. yet..",
            disability: "Not Mentioned",
            dp_image: "https://firebasestorage.googleapis.com/v0/b/firsttry-4edb6.appspot.com/o/images%2FFB_IMG_15183478212408759.jpg?alt=media&token=f4897d20-6c91-4fd1-ab9a-42388391a50d",
            follwed_by: [],
            gender: "male",
            location: "Sar-gojra, Chakwal",
            name: "Bamsi",
            notification_id: "786002",
            post_creator_email: "asddf@gmail.com",
            post_creator_name: "Naeem",
            post_id: "789177930002",
            post_status: "active",
            post_time: {date: 29, month: 6, year: 2020},
            region: "Punjab",
            status: "missing",
                  isReported: false,
      reported_by: 'none',
        },
        {
            age_group: "6-10 yrs",
            country: "Pakistan",
            description: "He is not missed.. yet..",
            disability: "Mentally Disable",
            dp_image: "/static/media/dummy_profile.1f7abd55.jpg",
            follwed_by: [],
            gender: "male",
            location: "12 - Block SGD",
            name: "Dogar",
            notification_id: "786003",
            post_creator_email: "asfdf@gmail.com",
            post_creator_name: "Hamza",
            post_id: "789177930003",
            post_status: "reported",
            post_time: {date: 3, month: 7, year: 2020},
            region: "Punjab",
            status: "found",
                  isReported: false,
      reported_by: 'none',
        },
]


export default dummy_posts;